apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan
  labels:
    app: loan
spec:
  selector:
    matchLabels:
      app: loan
  replicas: 1
  template:
    metadata:
      name: loan
      labels:
        app: loan
    spec:
      containers:
        - name: loan
          image: docker.io/k03147/loan
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "10004"
          ports:
            - name: port1
              containerPort: 10004
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loan
spec:
  type: ClusterIP
  selector:
    app: loan
  ports:
    - name: loan
      port: 10005
      targetPort: 10004
